"""add_user_role_expires_at_and_tenant_default_role

Revision ID: 058592027846
Revises: a1b2c3d4e5f6
Create Date: 2026-06-27 02:24:56.309592

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '058592027846'
down_revision: Union[str, Sequence[str], None] = 'a1b2c3d4e5f6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tenants', sa.Column('default_role', sa.String(length=50), nullable=True))
    op.add_column('user_roles', sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_roles', 'expires_at')
    op.drop_column('tenants', 'default_role')
    # ### end Alembic commands ###
