"""add profile fields city country dob bio

Revision ID: 499d77c40998
Revises: 470a9ca89590
Create Date: 2026-06-27 20:12:48.282529

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '499d77c40998'
down_revision: Union[str, Sequence[str], None] = '470a9ca89590'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('city', sa.String(length=100), nullable=True))
    op.add_column('users', sa.Column('country', sa.String(length=100), nullable=True))
    op.add_column('users', sa.Column('date_of_birth', sa.String(length=10), nullable=True))
    op.add_column('users', sa.Column('bio', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'bio')
    op.drop_column('users', 'date_of_birth')
    op.drop_column('users', 'country')
    op.drop_column('users', 'city')
    # ### end Alembic commands ###
