#!/bin/bash
# MyShop — CLI Установщик
# Запуск: curl -sSL https://install.myshop.com | bash
# Или: bash scripts/install.sh

set -e

RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
NC='\033[0m'

print_banner() {
    echo -e "${BLUE}"
    echo "  __  __           _ __  __ "
    echo " |  \/  |_   _ _ _| |  \/  |"
    echo " | |\/| | | | | '__| |\/| |"
    echo " | |  | | |_| | |  | |  | |"
    echo " |_|  |_|\__,_|_|  |_|  |_|"
    echo -e "${NC}"
    echo "  Internet Shop Platform"
    echo ""
}

check_requirements() {
    echo -e "${YELLOW}Checking requirements...${NC}"

    if ! command -v docker &> /dev/null; then
        echo -e "${RED}Docker not found. Installing...${NC}"
        curl -fsSL https://get.docker.com | sudo sh
        sudo usermod -aG docker $USER
        echo -e "${GREEN}Docker installed. Please logout and login again.${NC}"
        exit 1
    fi

    if ! command -v docker compose &> /dev/null; then
        echo -e "${RED}Docker Compose not found. Installing...${NC}"
        sudo apt install docker-compose-plugin -y
    fi

    echo -e "${GREEN}Requirements OK${NC}"
}

get_config() {
    echo -e "${BLUE}Configuration${NC}"
    echo ""

    read -p "Domain name (e.g., shop.example.com): " DOMAIN
    read -p "Admin email: " EMAIL
    read -p "License key (or 'demo'): " LICENSE_KEY

    if [ "$LICENSE_KEY" = "demo" ]; then
        LICENSE_KEY="MYSHOP-DEMO-$(openssl rand -hex 8)"
        echo -e "${YELLOW}Demo mode: $LICENSE_KEY${NC}"
    fi

    SECRET_KEY=$(openssl rand -base64 64)
    DB_PASSWORD=$(openssl rand -hex 16)
}

create_env() {
    echo -e "${YELLOW}Creating .env...${NC}"

    cat > .env << EOF
# MyShop Configuration
# Generated by install.sh on $(date)

SECRET_KEY=$SECRET_KEY
DATABASE_URL=postgresql+asyncpg://myshop:$DB_PASSWORD@db:5432/myshop
REDIS_URL=redis://redis:6379/0
RABBITMQ_URL=amqp://guest:guest@rabbitmq:5672/
HOST=0.0.0.0
PORT=8000
DEBUG=false
CORS_ORIGINS=["https://$DOMAIN"]
LICENSE_KEY=$LICENSE_KEY
EOF

    echo -e "${GREEN}.env created${NC}"
}

setup_ssl() {
    echo -e "${YELLOW}Setting up SSL...${NC}"

    if ! command -v certbot &> /dev/null; then
        sudo apt install certbot -y
    fi

    sudo certbot certonly --standalone \
        -d $DOMAIN -d www.$DOMAIN \
        --non-interactive --agree-tos \
        -m $EMAIL

    echo -e "${GREEN}SSL configured${NC}"
}

configure_nginx() {
    echo -e "${YELLOW}Configuring Nginx...${NC}"

    sed -i "s/yourdomain.com/$DOMAIN/g" deploy/nginx/default.conf

    echo -e "${GREEN}Nginx configured${NC}"
}

start_services() {
    echo -e "${YELLOW}Starting services...${NC}"

    docker compose -f docker-compose.prod.yml up -d

    echo -e "${GREEN}Services started${NC}"
}

print_summary() {
    echo ""
    echo -e "${GREEN}========================================${NC}"
    echo -e "${GREEN}  MyShop Installation Complete!${NC}"
    echo -e "${GREEN}========================================${NC}"
    echo ""
    echo -e "  ${BLUE}Site:${NC}       https://$DOMAIN"
    echo -e "  ${BLUE}Admin:${NC}      https://$DOMAIN/docs"
    echo -e "  ${BLUE}Login:${NC}      admin / admin123"
    echo ""
    echo -e "  ${YELLOW}Change admin password immediately!${NC}"
    echo ""
    echo -e "  ${BLUE}License:${NC}    $LICENSE_KEY"
    echo -e "  ${BLUE}Domain:${NC}     $DOMAIN"
    echo ""
    echo -e "  ${BLUE}Support:${NC}    support@myshop.com"
    echo -e "  ${BLUE}Docs:${NC}       https://docs.myshop.com"
    echo ""
}

# Main
print_banner
check_requirements
get_config
create_env
configure_nginx
setup_ssl
start_services
print_summary
